name: Release

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: true

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        run: corepack enable && pnpm -v

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm --filter astro-path-helpers build

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run ci:version
          commit: "[ci] release"
          title: "[ci] release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: pnpm exec changeset publish
        env:
          NPM_CONFIG_PROVENANCE: true

      - name: Push tags
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: git push --follow-tags
